spring:
  application:
    name: course-catalog-service
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    username: user
    password: pass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

message: Hello from default profile

#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#message: Hello from prod profile
#
#---
#spring:
#  config:
#    activate:
#      on-profile: non-prod
#message: Hello from prod profile
